### ISSUE TITLE
Emoji handshake  not working

### ISSUE THREAD

**Issue by ZoeMilena** [PoomSmart/EmojiPort-PE#11]
I installed Emojiport.  I installed the file manually via Filza.  everything works except for the handshake.  I have of course installed many tweaks.
![74688E1F-7FC1-4C1E-B0C7-43B12ABA16E5](https://user-images.githubusercontent.com/100304922/155368594-88803798-7773-4923-af06-1b4a8da05cb3.png)

**Comment by ZoeMilena** [comment]
I've already posted on github, but I found the bug.  I installed the version emojilibary 1.4.0-b1 and Emojiport 1.2.0-b2 and it works
![Uploading C12F6E57-D160-4D87-9BA7-277CF0E7D785.jpeg…]()

**Comment by PoomSmart** [comment]
Thanks for reporting although you missed lots of details to provide that could actually find out the root cause of that bug.
