### ISSUE TITLE
Causes crashes on Dopamine (A15, 15.2.1)

### ISSUE THREAD

**Issue by ZomkaDEV** [PoomSmart/EmojiPort-PE#13]
Hey all. I noticed that installing EmojiPort causes issues on my iPhone 13 mini. It causes random crashes out of no where. Uninstalling the tweak fixes this, so I assume it’s because of EmojiPort.

I could include crash logs and a list of tweaks installed but I’ll be honest, I’m not sure how to do that and I couldn’t really find how😅 (I’d be thankful if someone could explain how to do that to me🙂)

I hope this could be fixed! Thanks 🙂

**Comment by PoomSmart** [comment]
This is a stability issue specific to Dopamine/ElleKit itself.
