### ISSUE TITLE
Installing on iOS 12.4.1 crashes SpringBoard

### ISSUE THREAD

**Issue by ceilingtilefan** [PoomSmart/EmojiPort-PE#14]
A12, iOS 12.4.1, unc0ver jailbreak

SpringBoard crash log:
[SpringBoard-2024-02-17-101430.ips.txt](https://github.com/PoomSmart/EmojiPort-PE/files/14319478/SpringBoard-2024-02-17-101430.ips.txt)

**Comment by ceilingtilefan** [comment]
EmojiLibrary: `1.6.0~b1`
EmojiAttributes: `1.8.0~b1`
EmojiFontManager: `1.3.5`
EmojiPort (iOS 12.0-17.3): `1.5.0~b1`
EmojiPort Resources (iOS 10+): `1.6.0~b2`
AppleColorEmoji Unicode 15.1 (EFM): `15.1.0~b1`

**Comment by PoomSmart** [comment]
@bigfloppa234 Can you try this version of EmojiPort?

[com.ps.emojiportpe_1.5.0~b2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiPort-PE/files/14320965/com.ps.emojiportpe_1.5.0.b2_iphoneos-arm.deb.zip)

**Comment by ceilingtilefan** [comment]
It still crashes unfortunately. 

SpringBoard crash log:
[SpringBoard-2024-02-17-210603.ips.txt](https://github.com/PoomSmart/EmojiPort-PE/files/14320970/SpringBoard-2024-02-17-210603.ips.txt)

**Comment by PoomSmart** [comment]
@bigfloppa234 Try this too then.

[com.ps.emojiattributes_1.8.0~b1_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiPort-PE/files/14321049/com.ps.emojiattributes_1.8.0.b1_iphoneos-arm.deb.zip)

**Comment by ceilingtilefan** [comment]
Same issue

[SpringBoard-2024-02-18-103937.ips.txt](https://github.com/PoomSmart/EmojiPort-PE/files/14323500/SpringBoard-2024-02-18-103937.ips.txt)

**Comment by PoomSmart** [comment]
At this point I suspect it's a jailbreak/substitute issue. Also, the crashlog itself doesn't imply a lot which is typical for something possibly unrelated to the tweak.

**Comment by PoomSmart** [comment]
@bigfloppa234 How did you the crash log? And what is the version of Substitute installed on your phone?

**Comment by ceilingtilefan** [comment]
I don't understand what you're asking in the first question, sorry.

I have Substitute 2.3.1 installed

**Comment by PoomSmart** [comment]
"How did you get the crash log" = "Where did you get the txt file that you sent to me"

**Comment by ceilingtilefan** [comment]
I got it from the Analytics Data section in Settings

**Comment by PoomSmart** [comment]
@bigfloppa234 Can you test this version of EmojiAttributes?

[com.ps.emojiattributes_1.8.0~b2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiPort-PE/files/14353552/com.ps.emojiattributes_1.8.0.b2_iphoneos-arm.deb.zip)

**Comment by ceilingtilefan** [comment]
Springboard no longer crashes with that version of EmojiAttributes, but newer emojis show up like this 

![image](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/f1d6beb0-b10a-4e7f-a3a4-df19c24f881b)

**Comment by PoomSmart** [comment]
@bigfloppa234 Do you a Mac computer? I will need you to be able to retrive the system log for me, basically looking for any messages with the search filter "EmojiAttributes". Do you maybe a Discord account or something so I can guide if no clue.

**Comment by PoomSmart** [comment]
Also, did you enable the new emojis from EmojiFontManager tweak settings?

**Comment by ceilingtilefan** [comment]
Hi, I do have a Mac. How do I retrieve the system log? And I have enabled the new emojis from the tweak settings

**Comment by PoomSmart** [comment]
> Hi, I do have a Mac. How do I retrieve the system log? And I have enabled the new emojis from the tweak settings

Open Console app from your Mac. Connect your device to the Mac with the charging cable. Select your device from the left side of Console app. In the filter box on the right, type "EmojiAttributes" then click Start button to the left to start the logging. You should be able to see certain messages related to the tweak. Copy the messages to here.

**Comment by PoomSmart** [comment]
@bigfloppa234 You should be able to see messages related to "ICUHack" as well.

**Comment by ceilingtilefan** [comment]
Unfortunately, I don't see any messages for EmojiAttributes or ICUHack. However, I have noticed the latest iOS 17.4 emojis seem to work, but emojis from iOS 15.4 don't work.
![IMG_0151](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/8ce406df-3271-43fb-8490-20fdfd4d745f)

Console logs:
![Screenshot 2024-02-25 at 12 04 04 PM](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/d021fd13-6a38-4311-bd6a-9dffcb2603ae)
![Screenshot 2024-02-25 at 12 04 11 PM](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/adff03f7-7f15-46da-a880-2c45ef0ff752)

**Comment by PoomSmart** [comment]
@bigfloppa234 While on Console app like you shown in the images, close and reopen Notes app.

**Comment by ceilingtilefan** [comment]
Same problem, it doesn't show any logs

**Comment by PoomSmart** [comment]
[com.ps.emojiattributes_1.8.0~b2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiPort-PE/files/14455641/com.ps.emojiattributes_1.8.0.b2_iphoneos-arm.deb.zip)

@bigfloppa234 Use this version of EmojiAttributes instead.

**Comment by ceilingtilefan** [comment]
Interestingly, that version of EmojiAttributes fixed the issue. I get logs and iOS 15.4 emojis work now.
![IMG_0174](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/4aa9cd70-889b-4d4b-8af0-e48b095f739b)
Logs:
![Screenshot 2024-02-29 at 8 23 37 PM](https://github.com/PoomSmart/EmojiPort-PE/assets/104149053/91ffa4bc-77bd-468f-85af-f06eaf3bea2a)

**Comment by PoomSmart** [comment]
@bigfloppa234 Ok.. how about this version then?

[com.ps.emojiattributes_1.8.0~b2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiPort-PE/files/14455787/com.ps.emojiattributes_1.8.0.b2_iphoneos-arm.deb.zip)

**Comment by ceilingtilefan** [comment]
That version also works, emojis show up but I don't get logs in Console anymore

**Comment by PoomSmart** [comment]
Nice, I will publish a new version. Thanks for testing!
