### ISSUE TITLE
Version 1.5.0~b3 Causes issues with some pre-existing emojis

### ISSUE THREAD

**Issue by BeanFeed** [PoomSmart/EmojiPort-PE#15]
I am currently on iOS 15.1 with all the most up to date packages for EmojiPort, apart from the font package.
I have the font set to default, and in this instance, it causes the straight face emoji to act weird. It combines to emojis and types them at once. I have attached an image to show what I'm talking about.

![IMG_9668](https://github.com/PoomSmart/EmojiPort-PE/assets/86930720/4d901dce-6526-4e3e-bf21-1ac01ae899f0)
---------------

I tried downloading an older package but there is no releases published here and the history was removed on your github.io page. If I need to provide any more information, let me know.

**Comment by PoomSmart** [comment]
Font shouldn't be Default (Default means system default). Inside EmojiFontManager settings, set the font to AppleColorEmoji (or AppleColorEmoji_HD).
