### ISSUE TITLE
Not Works Anymore

### ISSUE THREAD

**Issue by CanerKaraca23** [PoomSmart/EmojiPort-PE#2]
Not works anymore on latest version.
iOS 12.4.6, iPhone 5s. iOS 13.2 emojis.

**Comment by PoomSmart** [comment]
Try reinstalling it?

**Comment by CanerKaraca23** [comment]
> Try reinstalling it?

I tried. Not works after you updated for iOS 14 update.

**Comment by PoomSmart** [comment]
What do you mean by "not working" ? Can you give me details?

**Comment by CanerKaraca23** [comment]
> What do you mean by "not working" ? Can you give me details?

After your update, iOS 13.2 emojis I used on my iOS 12.4.6 are disappeared, I mean no longer works after update.

**Comment by PoomSmart** [comment]
Do you use EmojiFontManager?

**Comment by CanerKaraca23** [comment]
> Do you use EmojiFontManager?

Yes, and I tried on SnowBoard still isn't showing 13.2 emojis after update.

**Comment by PoomSmart** [comment]
Could you try reinstalling EmojiLibrary?

**Comment by CanerKaraca23** [comment]
> Could you try reinstalling EmojiLibrary?

I tried but still isn't working. Btw I downgraded EmojiLibrary and EmojiPort but didn't worked again. Looks like update or something broked my emoji system :(

**Comment by PoomSmart** [comment]
All emojis just don’t show up or only new emojis don’t show up?

**Comment by CanerKaraca23** [comment]
> All emojis just don’t show up or only new emojis don’t show up?

Only new emojis.

**Comment by PoomSmart** [comment]
How about upgrading EmojiAttributes?

**Comment by CanerKaraca23** [comment]
Stil same.

**Comment by PoomSmart** [comment]
Can you send me screenshots of what your emoji keyboard looks like in certain applications?

**Comment by CanerKaraca23** [comment]
There should be some 13.2 emojis here

![5899AF9E-FFAE-43CA-8637-4ECCE474CC7E](https://user-images.githubusercontent.com/37447503/90337803-92b80c80-dfed-11ea-9816-dd6442700d10.jpeg)

**Comment by CanerKaraca23** [comment]
Thank you for your tweet.

https://www.reddit.com/r/jailbreak/comments/iasdzo/question_emojiport_suddenly_stopped_working_and/

I did this solution and it's working now.

![AA79DF50-5BC8-448C-8CFD-B66869C7D895](https://user-images.githubusercontent.com/37447503/90338155-27236e80-dff0-11ea-8169-50592ebaabd2.jpeg)

**Comment by CanerKaraca23** [comment]
EmojiPortPE is awesome project for old devices. Thank you.

I have a question about your HighGraphics tweak. What this tweak actually doing about graphics on old devices? There is no information on tweak page about version and devices.

Also can I suggest and request from you a tweak for iOS 12 and below devices? Can you make a tweak that adds this UI to older versions from iOS 13?

![5201FDC5-0F2B-43CB-9CDE-F2E6372967C7](https://user-images.githubusercontent.com/37447503/90338222-b466c300-dff0-11ea-9292-a74c41b7606a.jpeg)

**Comment by PoomSmart** [comment]
Well, HighGraphics forces the highest graphics settings for all UI elements for older devices.

I don't take requests nowadays, unfortunately.
