### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CanerKaraca23** [PoomSmart/EmojiPort-PE#5]
https://controlc.com/649be0de

infos are available in log

**Comment by PoomSmart** [comment]
Do you allow EmojiPort dylibs to run in Choicy?

**Comment by CanerKaraca23** [comment]
Yes, i didn't changed any setting so far. It occures after Emoji Library stable release. I updated it nothing happened but after rejeailbreaking, it always crashed.

**Comment by CanerKaraca23** [comment]
https://controlc.com/5ece4222

Still crashes after new update 1.0.9

**Comment by PoomSmart** [comment]
I am inclined this is jailbreak-related.

**Comment by CanerKaraca23** [comment]
> I am inclined this is jailbreak-related.

I'm using unc0ver 5.3.1 on iOS 12.4.8.

**Comment by parsifall** [comment]
Same for me, put my phone in Safe Mode (iPhone 7, iOS 12.0.1, unc0ver 5.3.1). Version 1.0.7~b6 worked fine. I can’t retrieve the deb anymore though :(

**Comment by CanerKaraca23** [comment]
> Same for me, put my phone in Safe Mode (iPhone 7, iOS 12.0.1, unc0ver 5.3.1). Version 1.0.7~b6 worked fine. I can’t retrieve the deb anymore though :(

You have iOS 14.2 fully working checkra1n jailbreak, why you staying on iOS 12?

**Comment by PoomSmart** [comment]
@CanerKaraca23 There are updates today, can you try?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 There are updates today, can you try?

Still crashing. New logs: https://controlc.com/ee152cd1

**Comment by PoomSmart** [comment]
@CanerKaraca23 Can you try 1.0.10~b2 or ~b3 ?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 Can you try 1.0.10~b2 or ~b3 ?

https://controlc.com/75e6ec4b
still crashes new log

**Comment by parsifall** [comment]
Latest beta (1.0.10~b3) fixes it for me!

**Comment by PoomSmart** [comment]
@CanerKaraca23 Is that from ~b3 ?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 Is that from ~b3 ?

Yes. Unfortunetly b3 not fixes my problem.

**Comment by CanerKaraca23** [comment]
1.0.10 not fixes my problem again.

https://controlc.com/a564974d

edit: and all tweaks disabled (only crashed and emojiportpe dependencies active) crash log

https://controlc.com/6f0680a3

**Comment by PoomSmart** [comment]
@CanerKaraca23 How about 1.0.11 ?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 How about 1.0.11 ?

😔
https://controlc.com/6f9438b1

Does it possibly have something to do with the EmojiLibrary? I seem to remember that this error occured after the EmojiLibrary update. I updated tweaks nothing happened but after re-jailbreak, it started to occure.

**Comment by PoomSmart** [comment]
Alright finally how about 1.0.11~b2? @CanerKaraca23

**Comment by CanerKaraca23** [comment]
> Alright finally how about 1.0.11~b2? @CanerKaraca23

Its working now! Thank you for your hard and long work.

![FCE99B40-5F9E-41B3-9B03-4EF7B0329A69](https://user-images.githubusercontent.com/37447503/99083575-c697d380-25d6-11eb-8a94-db0357c93506.png)
