### ISSUE TITLE
Notification Extensions from different apps crash

### ISSUE THREAD

**Issue by hero3210** [PoomSmart/EmojiPort-PE#8]
Since the new beta updates of EmojiPort, I’ve been having random crashes of different notification extensions. I noticed they happen at the same time a notification from the same application appears. 

Here’s a crash report of the notification extension of [Edison Mail](https://apps.apple.com/us/app/email-edison-mail/id922793622) app:
https://pastebin.com/Z0TxXFs4

I have more of this same crash & other crashes of notification extensions of other apps.

Thanks for all your hard work PoomSmart. Much appreciated.

**Comment by PoomSmart** [comment]
@hero3210 Is everything updated to the latest?

**Comment by hero3210** [comment]
> 

Yes 
(I also sent more crash reports to your hotmail)

**Comment by PoomSmart** [comment]
Fixed in 1.2.3
BTW, that hotmail has long been terminated.

**Comment by hero3210** [comment]
I see.. Good to know. Thanks.

Thanks so much.. everything is working now. Much appreciated.
