### ISSUE TITLE
EmpjiPortPE.dylib causes Iridium tweak to crash when decrypting any app

### ISSUE THREAD

**Issue by hero3210** [PoomSmart/EmojiPort-PE#9]
Device: iPhone X
iOS 14.3 - unc0ver 

EmojiPortPE: v1.2.2
EmojiAttributes: v1.5.0-b6
EmojiLibrary: v1.4.0-b2

iridium is an app decryption tweak. It is available in BigBoss. 
upon opening the iridium app & selecting any app to decrypt, a multitude of crashes will occur & all of them are caused by EmojiPortPE. 

Cr4shed crash log:
https://pastebin.com/p7mTzyr2

There is also a console screen in Iridium showing the decryption process as it happens, & it strangely shows “EmojiAttributes” a lot of times in the decryption process.

Thanks so much for your hard work.

**Comment by PoomSmart** [comment]
Fixed in EmojiPortPE 1.2.3

**Comment by hero3210** [comment]
Thanks so much.. everything is working now. Much appreciated.
